### ISSUE TITLE
Update to latest jsoneditor version

### ISSUE THREAD

**Issue by boiquach** [jackpocket/jsoneditor-rails#80]
I want to use this in my project and want to utilize some new methods from the newer versions of jsoneditor, would it be fine if i open a pull request to update to the latest version (by running the rake task)?

**Comment by javierjulio** [comment]
Yes it is. If you open that PR I'll take care of releasing it on Monday. Thank you!

**Comment by boiquach** [comment]
thank you, i will get to it when i can!

**Comment by boiquach** [comment]
I have opened a pull request, there's some other changes as well: https://github.com/jackpocket/jsoneditor-rails/pull/81

**Comment by boiquach** [comment]
@javierjulio  just want to say thank you so much for the gem and for releasing! this is a huge help for my project, really appreciate everything you've done😊

**Comment by javierjulio** [comment]
@boiquach you're very welcome! I'm glad you've found it useful as well. Thank you again for contributing.
